name: Desktop Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller hatch
        pip install -e .
        
    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: pyinstaller packaging/windows.spec
      
    - name: Build macOS
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller packaging/macos.spec
        chmod +x packaging/dmg/build_dmg.sh
        packaging/dmg/build_dmg.sh "dist/TG WS Proxy.app" "TG-Proxy" "dist/TG-Proxy-1.0.4-MAC.dmg"
      
    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev
        pyinstaller packaging/linux.spec
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.4
        name: "TG-Proxy-1.0.4"
        files: |
          dist/TG-Proxy-1.0.4-Linux
          dist/TG-Proxy-1.0.4-Windows.exe
          dist/TG-Proxy-1.0.4-MAC.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

